"""Initial schema

Revision ID: 01773fcf15b3
Revises:
Create Date: 2026-07-10 00:16:29.206307

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "01773fcf15b3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
